# Generated by Django 5.2.9 on 2025-12-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Home', max_length=200)),
                ('about_vertical_title', models.CharField(blank=True, max_length=120)),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('about_btn_text', models.CharField(blank=True, max_length=60)),
                ('about_btn_url', models.CharField(blank=True, max_length=300)),
                ('match_title', models.CharField(blank=True, max_length=200)),
                ('match_text', models.TextField(blank=True)),
                ('match_btn1_text', models.CharField(blank=True, max_length=60)),
                ('match_btn1_url', models.CharField(blank=True, max_length=300)),
                ('match_btn2_text', models.CharField(blank=True, max_length=60)),
                ('match_btn2_url', models.CharField(blank=True, max_length=300)),
                ('results_vertical_title', models.CharField(blank=True, max_length=120)),
                ('results_btn_text', models.CharField(blank=True, max_length=60)),
                ('results_btn_url', models.CharField(blank=True, max_length=300)),
                ('video_title', models.CharField(blank=True, max_length=200)),
                ('video_iframe_url', models.CharField(blank=True, max_length=500)),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='home/video/')),
                ('top_vertical_title', models.CharField(blank=True, max_length=120)),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('top_text', models.TextField(blank=True)),
                ('top_btn_text', models.CharField(blank=True, max_length=60)),
                ('top_btn_url', models.CharField(blank=True, max_length=300)),
                ('table_title', models.CharField(blank=True, max_length=200)),
                ('table_btn_text', models.CharField(blank=True, max_length=60)),
                ('table_btn_url', models.CharField(blank=True, max_length=300)),
                ('news_btn_text', models.CharField(blank=True, max_length=60)),
                ('news_btn_url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/slider/')),
                ('title_part1', models.CharField(blank=True, max_length=120)),
                ('title_part2', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('btn1_text', models.CharField(blank=True, max_length=60)),
                ('btn1_url', models.CharField(blank=True, max_length=300)),
                ('btn2_text', models.CharField(blank=True, max_length=60)),
                ('btn2_url', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='web.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('value', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='web.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
