# Generated by Django 5.2.9 on 2025-12-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_btn1_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn1_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn2_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn2_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_part1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_part2',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
