# Generated by Django 5.2.9 on 2025-12-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('location', models.CharField(choices=[('header_main_left', 'Хедер: главное меню слева'), ('header_main_right', 'Хедер: главное меню справа'), ('header_top_auth', 'Хедер: авторизация / корзина / поиск'), ('header_top_social', 'Хедер: соцсети'), ('mobile_main_left', 'Моб. меню: левая колонка'), ('mobile_main_right', 'Моб. меню: правая колонка'), ('footer_tags', 'Футер: популярные теги'), ('footer_bottom', 'Футер: нижнее меню')], max_length=50, unique=True, verbose_name='Зона вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('named_url', models.CharField(blank=True, help_text="Имя url из urls.py (reverse). Имеет приоритет над полем 'URL'.", max_length=100, verbose_name='Имя URL (reverse)')),
                ('url', models.CharField(blank=True, help_text='Абсолютный или относительный URL, если не используется имя роута.', max_length=255, verbose_name='URL')),
                ('icon_class', models.CharField(blank=True, help_text="Например: 'fa fa-shopping-cart', 'fa fa-facebook'.", max_length=100, verbose_name='CSS-класс иконки')),
                ('css_class', models.CharField(blank=True, help_text="Например: 'menu-item-has-children'.", max_length=100, verbose_name='Доп. CSS-класс')),
                ('html_attributes', models.TextField(blank=True, help_text='Например: data-toggle="modal" data-target="#tg-login". Выводится как есть в теге <a>.', verbose_name='Доп. HTML-атрибуты')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Открывать в новой вкладке')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='siteconfig.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='siteconfig.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SettingsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=True, help_text="Если включено, всем пользователям показывается страница 'сайт в разработке', кроме администраторов.", verbose_name='Сайт в разработке')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
