# Generated by Django 5.2.9 on 2025-12-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_menu_menuitem_settingsconfig_delete_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_es',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (ES)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_val',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (VAL)'),
        ),
    ]
